version: "2"

networks:
  app-tier:
    driver: bridge

services:
  cassandra_node_1:
    image: bitnami/cassandra:latest
    networks:
      - app-tier
    environment:
      - CASSANDRA_SEEDS= cassandra_node_1, cassandra_node_2, cassandra_node_3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    
  cassandra_node_2:
    image: bitnami/cassandra:latest
    networks:
      - app-tier
    environment:
      - CASSANDRA_SEEDS= cassandra_node_1, cassandra_node_2, cassandra_node_3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra


  cassandra_node_3:
    image: bitnami/cassandra:latest
    networks:
      - app-tier
    environment:
      - CASSANDRA_SEEDS= cassandra_node_1, cassandra_node_2, cassandra_node_3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

    
  api:
    build: ./API
    networks:
      - app-tier
    ports:
      - "5555:5555"
    depends_on:
      - cassandra_node_1
      - cassandra_node_2
      - cassandra_node_3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 30