version: '3.8'
networks:
  Sistem:
    driver: bridge
services:


  backendpython:
    build: ./Api/
    networks:
      - Sistem
    ports:
      - "3000:3000"

  cassandra-node1:
    image: bitnami/cassandra:4.0.4
    volumes:
      - ./cassandra-data:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    networks:
      - Sistem

  cassandra-node2:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    links:
      - cassandra-node1
    networks:
      - Sistem

  cassandra-node3:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    links:
      - cassandra-node1
    networks:
      - Sistem