version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  backend:
      build: ./Api
      environment:
        - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3 
        - CASSANDRA_USERNAME=cassandra
        - CASSANDRA_PASSWORD=cassandra 
      depends_on:
        - cassandra-node1
        - cassandra-node2
        - cassandra-node3
      restart: always
      ports:
        - "3000:3000"
      networks:
      - app-tier
  cassandra-node1:
    image: bitnami/cassandra:4.0.4
    volumes:
      - ./cassandra-data:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    networks:
      - app-tier

  cassandra-node2:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    links:
      - cassandra-node1
    networks:
      - app-tier

  cassandra-node3:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    links:
      - cassandra-node1
    networks:
      - app-tier