# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensaje.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmensaje.proto\"/\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\" \n\x08Response\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"\x1f\n\x0fGetItemsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t27\n\x0bItemService\x12(\n\x07GetItem\x12\x10.GetItemsRequest\x1a\t.Response\"\x00\x62\x06proto3')



_ITEM = DESCRIPTOR.message_types_by_name['Item']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_GETITEMSREQUEST = DESCRIPTOR.message_types_by_name['GetItemsRequest']
Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'mensaje_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'mensaje_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

GetItemsRequest = _reflection.GeneratedProtocolMessageType('GetItemsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETITEMSREQUEST,
  '__module__' : 'mensaje_pb2'
  # @@protoc_insertion_point(class_scope:GetItemsRequest)
  })
_sym_db.RegisterMessage(GetItemsRequest)

_ITEMSERVICE = DESCRIPTOR.services_by_name['ItemService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEM._serialized_start=17
  _ITEM._serialized_end=64
  _RESPONSE._serialized_start=66
  _RESPONSE._serialized_end=98
  _GETITEMSREQUEST._serialized_start=100
  _GETITEMSREQUEST._serialized_end=131
  _ITEMSERVICE._serialized_start=133
  _ITEMSERVICE._serialized_end=188
# @@protoc_insertion_point(module_scope)
