version: '3.7'

services:
  client:
    build: ./<ruta al cliente>
    depends_on:
      - postgres
      - server
    ports:
      - "80:3000"
  server:
    build: ./<ruta al servidor>
    depends_on:
      - postgres
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana